name: CI

on:
  push:
    branches: [main]
    tags-ignore: ["v?[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Lint files
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build extension
        run: pnpm build

      - name: Generate icon variants
        run: pnpm generate

      - name: Package extension
        uses: haaleo/publish-vscode-extension@v2
        with:
          pat: _
          dryRun: true
          dependencies: false
