name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Lint files
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build extension
        run: pnpm build

      - name: Generate icon variants
        run: pnpm generate

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        id: package
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

      - uses: abutler/upload-release-assets@v3.0
        with:
          files: ${{ steps.package.outputs.vsixPath }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
